[zsh]
.zshrc = ~/.zshrc

[ghostty]
config = ~/.config/ghostty/config

[starship]
starship.toml = ~/.config/starship.toml

[karabiner]
karabiner.json = ~/.config/karabiner/karabiner.json

[sublime]
Preferences.sublime-settings = ~/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings
Package Control.sublime-settings = ~/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings
Default (OSX).sublime-keymap = ~/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings

[tmux]
.tmux.conf = ~/.tmux.conf
