bind r source-file ~/.tmux.conf\; display "Config Reloaded"

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

set-option -g mouse on
bind -n S-Enter send-keys Escape "[13;2u"
